config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("", include("users.urls", namespace="users")),
]

mailing/urls.py
from django.urls import path

from .services import run_mailing
from .views import (
    HomePageView,
    MailingAttemptsListView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingRecipientCreateView,
    MailingRecipientDeleteView,
    MailingRecipientDetailView,
    MailingRecipientListView,
    MailingRecipientUpdateView,
    MailingUpdateView,
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    MessageUpdateView,
    UserListManagerView,
    toggle_mailing_activity,
    toggle_user_active_status,
)

app_name = "mailing"

urlpatterns = [
    # Главная страница
    path("", HomePageView.as_view(), name="home"),
    # Пути для получателей (клиентов)
    path("recipients/", MailingRecipientListView.as_view(), name="recipients"),
    path(
        "recipients/create/",
        MailingRecipientCreateView.as_view(),
        name="recipient_create",
    ),
    path(
        "recipients/<int:pk>/",
        MailingRecipientDetailView.as_view(),
        name="recipient_detail",
    ),
    path(
        "recipients/<int:pk>/update/",
        MailingRecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipients/<int:pk>/delete/",
        MailingRecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    # Пути для сообщений
    path("messages/", MessageListView.as_view(), name="messages"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path(
        "messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    # Пути для рассылок
    path("mailings/", MailingListView.as_view(), name="mailings"),
    path("mailings/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailings/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailings/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path(
        "mailings/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path("mailings/<int:pk>/run/", run_mailing, name="run_mailing"),
    path(
        "mailings/<int:pk>/toggle_activity/",
        toggle_mailing_activity,
        name="toggle_mailing_activity",
    ),
    # Путь для статистики попыток
    path("attempts/", MailingAttemptsListView.as_view(), name="mailing_attempts"),
    path("manager/users/", UserListManagerView.as_view(), name="user_list_manager"),
    path(
        "manager/users/<int:pk>/toggle-active/",
        toggle_user_active_status,
        name="toggle_user_active_status",
    ),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .forms import (
    CustomAuthenticationForm,
    CustomPasswordResetForm,
    CustomSetPasswordForm,
)
from .views import (
    RegisterView,
    UserProfileUpdateView,
    UserProfileView,
    email_verification,
)

app_name = "users"

urlpatterns = [
    path(
        "",
        auth_views.LoginView.as_view(
            template_name="users/login.html", form_class=CustomAuthenticationForm
        ),
        name="login",
    ),
    path("register/", RegisterView.as_view(), name="register"),
    path("confirm_email/<str:token>/", email_verification, name="email_confirm"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="mailing:home"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            form_class=CustomPasswordResetForm,
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=CustomSetPasswordForm,
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/edit/", UserProfileUpdateView.as_view(), name="profile_update"),
]

mailing/forms.py
from django import forms

from .models import Mailing, MailingRecipient, Message


class MailingRecipientForm(forms.ModelForm):
    class Meta:
        model = MailingRecipient
        fields = ["email", "full_name", "comment"]

    def __init__(self, *args, **kwargs):
        super(MailingRecipientForm, self).__init__(*args, **kwargs)
        self.fields["full_name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите Ф.И.О. клиента"}
        )
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "example@email.com"}
        )
        self.fields["comment"].widget.attrs.update(
            {
                "class": "form-control",
                "id": "exampleFormControlTextarea1",
                "rows": "4",
                "placeholder": "Введите комментарий (описание) по данному клиенту",
            }
        )


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["email_subject", "email_body"]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields["email_subject"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите тему сообщения "}
        )
        self.fields["email_body"].widget.attrs.update(
            {
                "class": "form-control",
                "id": "exampleFormControlTextarea1",
                "rows": "4",
                "placeholder": "Введите текст сообщения",
            }
        )


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ["message", "recipients", "start_time", "end_time"]
        widgets = {
            "start_time": forms.DateTimeInput(
                attrs={"type": "datetime-local", "class": "form-control"}
            ),
            "end_time": forms.DateTimeInput(
                attrs={"type": "datetime-local", "class": "form-control"}
            ),
            "recipients": forms.CheckboxSelectMultiple(
                attrs={"class": "form-check-input"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields["message"].widget.attrs.update(
            {
                "class": "form-select form-select-sm",
                "aria-label": "Small select example",
            }
        )

mailing/views.py
import logging

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import (
    AccessMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.core.cache import cache
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from config.settings import EMAIL_HOST_USER, LOGIN_URL

from .forms import MailingForm, MailingRecipientForm, MessageForm
from .models import Mailing, MailingAttempt, MailingRecipient, Message

logger = logging.getLogger(__name__)
User = get_user_model()


class ManagerRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if (
            not request.user.is_superuser
            and not request.user.groups.filter(name="Менеджер").exists()
        ):
            messages.error(request, "У вас нет прав для доступа к этой странице.")
            return redirect("mailing:home")
        return super().dispatch(request, *args, **kwargs)


def manager_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(LOGIN_URL)
        if (
            not request.user.is_superuser
            and not request.user.groups.filter(name="Менеджер").exists()
        ):
            messages.error(request, "У вас нет прав для доступа к этой странице.")
            return redirect("mailing:home")
        return view_func(request, *args, **kwargs)

    return _wrapped_view


# Контроллеры для управления получателями рассылки
@method_decorator(cache_page(60), name="dispatch")
class MailingRecipientListView(LoginRequiredMixin, ListView):
    model = MailingRecipient
    template_name = "mailing/recipients_list.html"
    context_object_name = "recipients"

    def get_queryset(self):
        if (
            self.request.user.groups.filter(name="Менеджер").exists()
            or self.request.user.is_superuser
        ):
            return MailingRecipient.objects.all()
        return MailingRecipient.objects.filter(owner=self.request.user)


@method_decorator(cache_page(60), name="dispatch")
class MailingRecipientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = MailingRecipient
    template_name = "mailing/recipient.html"

    def test_func(self):
        if (
            self.request.user.groups.filter(name="Менеджер").exists()
            or self.request.user.is_superuser
        ):
            return True
        obj = self.get_object()
        return obj.owner == self.request.user


class MailingRecipientCreateView(LoginRequiredMixin, CreateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    template_name = "mailing/recipient_form.html"
    success_url = reverse_lazy("mailing:recipients")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        response = super().form_valid(form)
        cache.delete(reverse("mailing:recipients"))
        return response


class MailingRecipientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    template_name = "mailing/recipient_form.html"
    success_url = reverse_lazy("mailing:recipients")

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_superuser

    def form_valid(self, form):
        response = super().form_valid(form)
        cache.delete(reverse("mailing:recipients"))
        cache.delete(reverse("mailing:recipient_detail", kwargs={"pk": self.object.pk}))
        return response


class MailingRecipientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = MailingRecipient
    context_object_name = "recipient"
    template_name = "mailing/recipient_confirm_delete.html"
    success_url = reverse_lazy("mailing:recipients")

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_superuser

    def form_valid(self, form):
        pk_to_delete = self.get_object().pk
        response = super().form_valid(form)
        cache.delete(reverse("mailing:recipients"))
        cache.delete(reverse("mailing:recipient_detail", kwargs={"pk": pk_to_delete}))
        return response


# Контроллеры для управления сообщениями
@method_decorator(cache_page(60), name="dispatch")
class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = "mailing/messages.html"
    context_object_name = "messages"

    def get_queryset(self):
        if (
            self.request.user.groups.filter(name="Менеджер").exists()
            or self.request.user.is_superuser
        ):
            return Message.objects.all()
        return Message.objects.filter(owner=self.request.user)


@method_decorator(cache_page(60), name="dispatch")
class MessageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Message
    template_name = "mailing/message.html"

    def test_func(self):
        if (
            self.request.user.groups.filter(name="Менеджер").exists()
            or self.request.user.is_superuser
        ):
            return True
        obj = self.get_object()
        return obj.owner == self.request.user


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = "mailing/message_form.html"
    success_url = reverse_lazy("mailing:messages")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        response = super().form_valid(form)
        cache.delete(reverse("mailing:messages"))
        return response


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = "mailing/message_form.html"
    success_url = reverse_lazy("mailing:messages")

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_superuser

    def form_valid(self, form):
        response = super().form_valid(form)
        cache.delete(reverse("mailing:messages"))
        cache.delete(reverse("mailing:message_detail", kwargs={"pk": self.object.pk}))
        return response


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Message
    context_object_name = "message"
    template_name = "mailing/message_confirm_delete.html"
    success_url = reverse_lazy("mailing:messages")

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_superuser

    def form_valid(self, form):
        pk_to_delete = self.get_object().pk
        response = super().form_valid(form)
        cache.delete(reverse("mailing:messages"))
        cache.delete(reverse("mailing:message_detail", kwargs={"pk": pk_to_delete}))
        return response


# Контроллеры для управления рассылкой
@method_decorator(cache_page(60), name="dispatch")
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = "mailing/mailings.html"
    context_object_name = "mailings"

    def get_queryset(self):
        if (
            self.request.user.groups.filter(name="Менеджер").exists()
            or self.request.user.is_superuser
        ):
            return Mailing.objects.all()
        return Mailing.objects.filter(owner=self.request.user)


@method_decorator(cache_page(60), name="dispatch")
class MailingDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Mailing
    template_name = "mailing/mailing.html"

    def test_func(self):
        if (
            self.request.user.groups.filter(name="Менеджер").exists()
            or self.request.user.is_superuser
        ):
            return True
        obj = self.get_object()
        return obj.owner == self.request.user


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy("mailing:mailings")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.status = Mailing.STATUS_CREATED
        form.instance.is_active = True
        response = super().form_valid(form)
        cache.delete(reverse("mailing:mailings"))
        return response


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy("mailing:mailings")

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_superuser

    def form_valid(self, form):
        response = super().form_valid(form)
        cache.delete(reverse("mailing:mailings"))
        cache.delete(reverse("mailing:mailing_detail", kwargs={"pk": self.object.pk}))
        return response


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    context_object_name = "mailing"
    template_name = "mailing/mailing_confirm_delete.html"
    success_url = reverse_lazy("mailing:mailings")

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_superuser

    def form_valid(self, form):
        pk_to_delete = self.get_object().pk

mailing/templates/mailing/adding_mailing_attempt.html
{% extends 'mailing/base.html' %}

{% block content %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Отправка рассылки</title>
</head>
<body>
    <h1>Отправить рассылку</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
</body>
</html>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% block title %}Главная{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Django-project</p>
</div>

<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <h3 class="text-center mb-4">Общая статистика</h3>
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'mailing:mailings' %}">Всего создано рассылок:</a>
                <span class="badge bg-dark rounded-pill">{{ count_mailing }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'mailing:mailings' %}" title="Перейти к списку активных рассылок">Количество активных рассылок:</a>
                <span class="badge bg-dark rounded-pill">{{ active_mailings_count }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'mailing:recipients' %}">Количество уникальных получателей:</a>
                <span class="badge bg-dark rounded-pill">{{ unique_recipients_count }}</span>
            </li>
        </ul>
    </div>
</div>

<div class="d-grid gap-2 d-md-flex justify-content-md-end mt-4">
    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_attempts' %}" role="button">Статистика Ваших рассылок</a>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}" role="button">Добавить рассылку</a>
</div>

{% endblock %}

mailing/templates/mailing/inc_menu.html
<header class="p-3 bg-light border-bottom shadow-sm">
    <div class="container-fluid">
        <nav class="navbar navbar-light bg-light p-0 d-flex justify-content-between align-items-center">

            <a class="navbar-brand" href="{% url 'mailing:home' %}">
                <span class="fs-5 fw-bold">Django-project</span>
            </a>

            <ul class="navbar-nav d-flex flex-row">
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:home' %}">Главная</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:recipients' %}">Клиенты</a>
                </li>
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:messages' %}">Сообщения</a>
                </li>
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:mailings' %}">Рассылки</a>
                </li>
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_attempts' %}">Статистика</a>
                </li>
                {% if is_manager %}
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:user_list_manager' %}">Пользователи</a>
                </li>
                {% endif %}
                {% endif %}
            </ul>


            <ul class="navbar-nav d-flex flex-row">
                {% if user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
                </li>
                <li class="nav-item">
                    <form method="post" action="{% url 'users:logout' %}" class="d-flex">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary">Выйти</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item me-2">
                    <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

mailing/templates/mailing/mailings.html
{% extends 'mailing/base.html' %}
{% block title %}Список рассылок{% endblock %}

{% block content %}
<div class="container marketing mt-5">
    <div class="container text-center mt-3">
        <div class="row justify-content-center">
            <div class="col-4 mb-2">
                <h2>Рассылки</h2>
                {% if user.is_authenticated %}
                <a class="btn btn-success mt-3" href="{% url 'mailing:mailing_create' %}">Создать рассылку</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="table-responsive small">
            <table class="table table-success table-striped">
                <thead>
                <tr>
                    <th>Тема сообщения</th>
                    <th>Начата</th>
                    <th>Окончена</th>
                    <th>Статус</th>
                    <th>Сообщение</th>
                    <th>Активность</th>
                    <th>Создал</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                {% for mailing in mailings %}
                <tr>
                    <td>{{ mailing.message.email_subject }}</td>
                    <td>{{ mailing.start_time|date:"d M Y" }}</td>
                    <td>{{ mailing.end_time|date:"d M Y" }}</td>
                    <td>{{ mailing.get_status_display }}</td>
                    <td>{{ mailing.message.email_body|truncatechars:30 }}</td>
                    <td>
                        {% if mailing.is_active %}
                        <span class="badge bg-success">Активна</span>
                        {% else %}
                        <span class="badge bg-secondary">Не активна</span>
                        {% endif %}

                        {% if is_manager %}
                        <a type="button"
                           class="btn {% if mailing.is_active %}btn-danger{% else %}btn-success{% endif %} btn-sm mt-1"
                           href="{% url 'mailing:toggle_mailing_activity' mailing.pk %}">
                            {% if mailing.is_active %}Заблокировать{% else %}Разблокировать{% endif %}
                        </a>
                        {% endif %}
                    </td>
                    <td>{{ mailing.owner.email|default:"N/A" }}</td>

                    <td>
                        <a class="btn btn-primary btn-sm" href="{% url 'mailing:mailing_detail' mailing.pk %}">Посмотреть </a>

                        {% if mailing.owner == user or user.is_superuser %}
                        <a class="btn btn-primary btn-sm" href="{% url 'mailing:mailing_update' mailing.pk %}">Редактировать</a>
                        <a class="btn btn-danger btn-sm"
                           href="{% url 'mailing:mailing_delete' mailing.pk %}">Удалить</a>
                        {% endif %}

                        {% if mailing.is_active %}
                        {% if mailing.is_active and is_manager %}
                        <a class="btn btn-success btn-sm" href="{% url 'mailing:run_mailing' mailing.pk %}">Запустить</a>
                        {% else %}
                        <button class="btn btn-secondary btn-sm" disabled>Запустить</button>
                        {% endif %}
                        {% else %}
                        <button class="btn btn-secondary btn-sm" disabled>Запустить</button>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message.html
{% extends 'mailing/base.html' %}
{% block title %}Информация о сообщении{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Информация о сообщении {{ object.email_subject }} для рассылки</h1>
</div>
<div class="col-lg-12 col-md-6 col-sm-12">
    <div class="card">
        <h2 class="card-header p-3 text-center">{{ object.email_subject }}</h2>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Текст сообщения: {{object.email_body}}</li>
            <li class="list-group-item">Менеджер: {{object.owner.last_name}} {{object.owner.first_name}}</li>
        </ul>
        <a href="{% url 'mailing:message_update' message.pk %}" class="btn btn-outline-primary m-2 text-center" role="button" style="max-width: 255px;">
            Редактировать</a>
        <a href="{% url 'mailing:message_delete' message.pk %}" class="btn btn-outline-danger m-2 text-center" role="button" style="max-width: 255px;">
            Удалить</a>
    </div>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a class="btn btn-outline-primary mt-4" href="{% url 'mailing:messages' %}" role="button" style="max-width: 215px;">Назад</a>
</div>
{% endblock %}

mailing/templates/mailing/recipient.html
{% extends 'mailing/base.html' %}
{% block title %}Информация о {{ object.full_name }}{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Информация о получателе рассылки</h1>
</div>
<div class="col-lg-12 col-md-6 col-sm-12">
    <div class="card">
        <h2 class="card-header p-3 text-center">{{ object.full_name }}</h2>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Описание: {{object.comment}}</li>
            <li class="list-group-item">Действующий: {{object.is_active|yesno:"Да,Нет"}}</li>
            <li class="list-group-item">Менеджер: {{object.owner.last_name}} {{object.owner.first_name}}</li>
        </ul>
        <a href="{% url 'mailing:recipient_update' object.pk %}"
           class="btn btn-outline-primary m-2 text-center" role="button" style="max-width: 255px;">
            Редактировать</a>
        <a href="{% url 'mailing:recipient_delete' object.pk %}"
           class="btn btn-outline-danger m-2 text-center" role="button" style="max-width: 255px;">
            Удалить</a>
    </div>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a class="btn btn-outline-primary mt-4" href="{% url 'mailing:recipients' %}" role="button" style="max-width: 215px;">Назад</a>
</div>
{% endblock %}

mailing/templates/mailing/user_list_manager.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="container my-5">
    <div class="row">
        <div class="col-12 text-center">
            <h2 class="mb-4">Список пользователей сервиса</h2>
        </div>
    </div>
</div>
        {% if users %}
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Email</th>
                        <th>Имя</th>
                        <th>Активен?</th>
                        <th>Роли</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.pk }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.first_name }} {{ user.last_name }}</td>
                            <td>
                                {% if user.is_active %}
                                    <span class="badge bg-success">Да</span>
                                {% else %}
                                    <span class="badge bg-danger">Нет</span>
                                {% endif %}
                            </td>
                            <td>
                                {% for group in user.groups.all %}
                                    {{ group.name }}{% if not forloop.last %}, {% endif %}
                                {% empty %}
                                    Нет ролей
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'mailing:toggle_user_active_status' user.pk %}"
                                   class="btn btn-{% if user.is_active %}danger{% else %}success{% endif %} btn-sm">
                                    {% if user.is_active %}Заблокировать{% else %}Разблокировать{% endif %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="text-center">Пользователей не найдено (или вы не можете просматривать их).</p>
        {% endif %}
    </div>
{% endblock %}