config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("", include("users.urls", namespace="users")),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .forms import (
    CustomAuthenticationForm,
    CustomPasswordResetForm,
    CustomSetPasswordForm,
)
from .views import (
    RegisterView,
    UserProfileUpdateView,
    UserProfileView,
    email_verification,
)

app_name = "users"

urlpatterns = [
    path(
        "",
        auth_views.LoginView.as_view(
            template_name="users/login.html", form_class=CustomAuthenticationForm
        ),
        name="login",
    ),
    path("register/", RegisterView.as_view(), name="register"),
    path("confirm_email/<str:token>/", email_verification, name="email_confirm"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="mailing:home"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            form_class=CustomPasswordResetForm,
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=CustomSetPasswordForm,
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/edit/", UserProfileUpdateView.as_view(), name="profile_update"),
]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Пользователи должны иметь email-адрес")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Суперпользователь должен иметь is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Суперпользователь должен иметь is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name="Адрес электронной почты")
    avatar = models.ImageField(upload_to="users/photos", null=True, blank=True, verbose_name="Фото профиля")
    phone_number = models.CharField(max_length=11, blank=True, null=True, verbose_name="Номер телефона")
    country = models.CharField(max_length=100, blank=True, verbose_name="Страна")

    username = None

    token = models.CharField(max_length=150, blank=True, null=True, verbose_name="Токен для верификации")
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()


    def __str__(self):
        return self.email


    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ["email", "last_name", "first_name", "phone_number", "country", "create_at", ]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm,
    UserCreationForm,
)

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "example@email.com"}
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Ваш пароль"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Повторите пароль"}
        )
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Ваш email"}
        )
        self.fields["password"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Ваш пароль"}
        )

        self.fields["username"].label = "Email адрес"
        self.fields["password"].label = "Пароль"


class CustomPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Ваш Email"}
        )
        self.fields["email"].label = "Email-адрес"


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["new_password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите новый пароль"}
        )
        self.fields["new_password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Повторите новый пароль"}
        )

        self.fields["new_password1"].label = "Новый пароль"
        self.fields["new_password2"].label = "Повторите пароль"


class UserProfileForm(forms.ModelForm):
    """ Форма для редактирования профиля пользователя """

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'avatar', 'phone_number', 'country')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваша фамилия'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'Ваш Email', 'readonly': 'readonly'}),
            # Можно сделать только для чтения
            'phone_number': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Например, 79XXXXXXXXX', 'pattern': '[0-9]{11}'}),
            # Добавляем паттерн для 11 цифр
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Например, Россия'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Email',
            'phone_number': 'Номер телефона',
            'country': 'Страна',
            'avatar': 'Фото профиля',
        }
        help_texts = {
            'phone_number': 'Введите 11 цифр без пробелов и символов. Например, 79123456789.',
            'avatar': 'Загрузите изображение для вашего профиля.',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['email'].disabled = True

        for field_name, field in self.fields.items():
            if isinstance(field.widget, (
            forms.TextInput, forms.EmailInput, forms.NumberInput, forms.URLInput, forms.PasswordInput, forms.Textarea,
            forms.FileInput, forms.Select)):
                field.widget.attrs['class'] = 'form-control'
            elif isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            if 'placeholder' not in field.widget.attrs and field.label:
                field.widget.attrs['placeholder'] = field.label

users/views.py
import logging
import secrets

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from .forms import UserProfileForm, UserRegisterForm

logger = logging.getLogger(__name__)
User = get_user_model()


class RegisterView(SuccessMessageMixin, CreateView):
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")
    success_message = (
        "Ваша учетная запись успешно создана. Пожалуйста, подтвердите свой Email."
    )

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(32)
        user.token = token
        user.save()
        host = self.request.get_host()
        confirmation_url_path = reverse("users:email_confirm", kwargs={"token": token})
        url_for_confirm = f"{self.request.scheme}://{host}{confirmation_url_path}"
        send_mail(
            subject="Подтвердите вашу электронную почту.",
            message=f"Для активации вашей учетной записи пройдите по ссылке {url_for_confirm}.",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    try:
        user = get_object_or_404(User, token=token)
    except User.DoesNotExist:
        messages.error(
            request,
            "Неверная ссылка для активации. Возможно, токен уже использован или некорректен.",
        )
        return redirect(reverse("users:register"))

    if user.is_active:
        messages.info(request, "Ваша учетная запись уже активна.")
        user.token = None
        user.save()
        return redirect(reverse("mailing:home"))

    user.is_active = True
    user_group, created = Group.objects.get_or_create(name="Пользователь")
    user.groups.add(user_group)
    user.token = None
    user.save()

    subject = f"Добро пожаловать в наш сервис, {user.last_name} {user.first_name}."
    message = f"Здравствуйте {user.last_name} {user.first_name}! Спасибо, что зарегистрировались в нашем сервисе!"
    from_email = settings.EMAIL_HOST_USER
    recipient_list = [user.email]
    send_mail(subject, message, from_email, recipient_list)

    messages.success(request, "Ваша учетная запись успешно активирована!")
    return redirect(reverse("mailing:home"))


class UserProfileView(LoginRequiredMixin, DetailView):
    """Контроллер для просмотра профиля текущего пользователя"""

    model = User
    template_name = "users/profile.html"
    context_object_name = "user_profile"

    def get_object(self, queryset=None):
        """Возвращает объект профиля текущего авторизованного пользователя"""
        return self.request.user


class UserProfileUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """Контроллер для редактирования профиля текущего пользователя"""

    model = User
    form_class = UserProfileForm
    template_name = "users/profile_form.html"
    success_url = reverse_lazy("users:profile")
    success_message = "Ваш профиль успешно обновлен!"

    def get_object(self, queryset=None):
        """Возвращает объект профиля текущего авторизованного пользователя для редактирования"""
        return self.request.user

    def get_form_kwargs(self):
        """Добавляет request.user в аргументы формы, если форма должна
        выполнять какие-либо проверки на основе текущего пользователя"""
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.request.user
        return kwargs

    def form_valid(self, form):
        return super().form_valid(form)

users/templates/users/email_confirmation.html
<p>Привет, {{ user.username }}!</p>

<p>Спасибо за регистрацию на нашем сайте. Пожалуйста, подтвердите свой адрес электронной почты, перейдя по следующей ссылке:</p>

<p><a href="{{ confirm_link }}">{{ confirm_link }}</a></p>

<p>Если вы не регистрировались на нашем сайте, просто проигнорируйте это письмо.</p>

<p>С уважением,</p>
<p>Команда Django-project</p>

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Вход</h1>
</div>

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                {% if form.errors %}
                    <p class="alert alert-danger">Ваше имя пользователя и пароль не совпали. Пожалуйста, попробуйте еще раз.</p>
                {% endif %}

                {% if next %}
                    {% if user.is_authenticated %}
                        <p class="alert alert-warning">У вас нет доступа к этой странице. Пожалуйста, войдите с другой учетной записью.</p>
                    {% else %}
                        <p class="alert alert-info">Пожалуйста, войдите, чтобы увидеть эту страницу.</p>
                    {% endif %}
                {% endif %}

                <form method="post" action="{% url 'users:login' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя:</label>
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.password.id_for_label }}" class="form-label">Пароль:</label>
                        {{ form.password }}
                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
                <p class="mt-3">
                    <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'mailing/base.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Вы вышли из системы</h1>
</div>
<div class="row justify-content-center">
    <div class="col-md-6 text-center">
        <p>Вы успешно вышли из своей учетной записи.</p>
        <p><a href="{% url 'users:login' %}">Войти снова</a></p>
        <p><a href="{% url 'mailing:home' %}">На главную</a></p>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Пароль успешно сброшен!</h2>
                </div>
                <div class="card-body">
                    <p class="text-center">Ваш пароль успешно изменен. Теперь вы можете войти в систему с новым паролем.</p>
                    <div class="d-grid gap-2">
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Установить новый пароль</h2>
            </div>
            <div class="card-body">
                {% if validlink %}
                <form method="post">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <div class="mb-3">
                        {{ form.new_password1 }}
                        {% if form.new_password1.errors %}
                        <div class="invalid-feedback d-block">
                            {% for error in form.new_password1.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.new_password2 }}
                        {% if form.new_password2.errors %}
                        <div class="invalid-feedback d-block">
                            {% for error in form.new_password2.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary">Установить пароль</button>
                    </div>
                </form>
                {% else %}
                <div class="alert alert-danger" role="alert">
                    <p class="text-center">Ссылка для сброса пароля недействительна или уже использована. Пожалуйста,
                        запросите сброс снова.</p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Письмо для сброса пароля отправлено</h2>
            </div>
            <div class="card-body">
                <p class="text-center">Мы отправили вам инструкции по сбросу пароля на ваш Email-адрес. Пожалуйста,
                    проверьте свою почту (включая папки со спамом).</p>
                <p class="text-center">Если вы не получили письмо, попробуйте еще раз или свяжитесь с нами.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
Здравствуйте,

Вы (или кто-то еще) запросили сброс пароля для вашей учетной записи на сайте Django-project.

Пожалуйста, перейдите по следующей ссылке, чтобы сбросить ваш пароль:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.

Спасибо,
Команда Django-project

users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Сброс пароля</h2>
            </div>
            <div class="card-body">
                <p class="text-center">Забыли пароль? Введите свой Email, и мы отправим вам инструкции по его
                    сбросу.</p>
                <form method="post">
                    {% csrf_token %}

                    {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        {{ error }}
                        {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <div class="mb-3">
                        {{ form.email }}
                        {% if form.email.errors %}
                        <div class="invalid-feedback d-block">
                            {% for error in form.email.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary">Сбросить пароль</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'mailing/base.html' %}
{% block title %}Мой профиль{% endblock %}

{% block content %}
<div class="container marketing mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Профиль пользователя: {{ user_profile.first_name }} {{ user_profile.last_name }}</h2>
                </div>
                <div class="card-body">
                    {% if user_profile.avatar %}
                    <div class="text-center mb-3">
                        <img src="{{ user_profile.avatar.url }}" alt="Аватар профиля" class="img-fluid rounded-circle"
                             style="max-width: 150px; height: 150px; object-fit: cover;">
                    </div>
                    {% else %}
                    <div class="text-center mb-3">
                        <p>Аватар не установлен.</p>
                    </div>
                    {% endif %}

                    <p><strong>Email:</strong> {{ user_profile.email }}</p>
                    <p><strong>Имя:</strong> {{ user_profile.first_name|default:"Не указано" }}</p>
                    <p><strong>Фамилия:</strong> {{ user_profile.last_name|default:"Не указано" }}</p>
                    <p><strong>Номер телефона:</strong> {{ user_profile.phone_number|default:"Не указан" }}</p>
                    <p><strong>Страна:</strong> {{ user_profile.country|default:"Не указана" }}</p>
                    <p><strong>Дата регистрации:</strong> {{ user_profile.date_joined|date:"d M Y H:i" }}</p>
                    <p><strong>Последнее обновление профиля:</strong> {{ user_profile.updated_at|date:"d M Y H:i" }}</p>
                    <p><strong>Активен:</strong> {% if user_profile.is_active %}Да{% else %}Нет{% endif %}</p>

                    <div class="text-center mt-4">
                        <a href="{% url 'users:profile_update' %}" class="btn btn-primary">Редактировать профиль</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_form.html
{% extends 'mailing/base.html' %}
{% block title %}Редактировать профиль{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-lg border-0 rounded-lg">
                <div class="card-header bg-primary text-white text-center py-4 rounded-top-lg">
                    <h2 class="h3 mb-0">Редактировать профиль</h2>
                </div>
                <div class="card-body p-4">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-4">
                            <button type="submit" class="btn btn-success btn-lg me-md-2">Сохранить изменения</button>
                            <a href="{% url 'users:profile' %}" class="btn btn-secondary btn-lg">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Регистрация</h1>
</div>

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}:</label>
                        {{ field }}
                        {% if field.errors %}
                        <div class="invalid-feedback d-block">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}